### ISSUE TITLE
Where can I see the 'Mixed Cross Entropy Loss' codes?

### ISSUE THREAD

**Issue by NTDXYG** [haorannlp/mix#1]
Hello authors, I think your work is very interesting and far-reaching. However, I am not sure about the code implementation of 'Mixed Cross Entropy Loss' in your open source code. Could you please explain where I can see the code implementation of Mixed Cross Entropy Loss？

**Comment by haorannlp** [comment]
> Hello authors, I think your work is very interesting and far-reaching. However, I am not sure about the code implementation of 'Mixed Cross Entropy Loss' in your open source code. Could you please explain where I can see the code implementation of Mixed Cross Entropy Loss？

Hi, pls check `fairseq/criterions/oracle_label_smoothed_cross_entropy.py` and `fairseq/models/oracle_transformer.py`

**Comment by NTDXYG** [comment]
Thanks!
